# Generated by Django 4.2.30 on 2026-07-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinglife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotation',
            name='frais_bateau',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotation',
            name='montant_apres_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotation',
            name='montant_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotation',
            name='montant_sous_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotation',
            name='remise_pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
