# Generated by Django 4.2.30 on 2026-07-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinglife', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantite_commandee', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('quantite_livree', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unite', models.CharField(default='unité', max_length=50)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinglife.article')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='kinglife.facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
    ]
