# Generated by Django 4.2.30 on 2026-07-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinglife', '0004_lignefacture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignefacture',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='lignefacture',
            old_name='article',
            new_name='article_catalogue',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='quantite_commandee',
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='quantite_demandee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='quantite_livree',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='unite',
            field=models.CharField(default='Unité', max_length=50),
        ),
    ]
